[package]
name = "plugin-package"
description = "Package for plugin"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw_storage_plus = { workspace = true }
